add_newline = true

format = """$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$golang\
$jobs\
$line_break\
$character"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_replace_symbol = "[^](bold green)"
vimcmd_visual_symbol = "[V](bold green)"

[directory]
truncation_length = 4
truncate_to_repo = true
truncation_symbol = ""

[git_branch]
symbol = ""
format = "[$branch]($style) "
truncation_length = 32
truncation_symbol = ".."

[git_status]
format = '([$all_status$ahead_behind]($style))'
staged = "+${count} "
modified = "~${count} "
untracked = "?${count} "
deleted = "-${count} "
conflicted = "!${count} "
stashed = "*${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇡${ahead_count}⇣${behind_count} "

[status]
disabled = true

[jobs]
format = "[$number]($style) "
number_threshold = 1
symbol_threshold = 0

[nodejs]
disabled = false

[python]
disabled = false

[golang]
disabled = false

[rust]
disabled = true

[java]
disabled = true
